version: '3'
services:
  redcap:
    container_name: redcap
    image: andy123/redcap-docker
    ports:
      - "20080:80"
      - "23306:3306"
    volumes:
      - ${WEBROOT_DIR}:/redcap_webroot"
      - ${MYSQL_DIR}:/var/lib/mysql"
      - ${LOGS_DIR}:/var/log/export"
    links:
      - "mailhog:mailhog"
    depends_on:
      - mailhog
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025"
      - "81:8025"
volumes:
  webroot:
  mysql:
  logs: