version: '3'
services:

  web:
    build: docker-web
    env_file: .env
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./override-web:/etc/container-config-override
      - ${WEBROOT_DIR}:/var/www/html
      - ${LOGS_DIR}:/var/log/apache2

  db:
    image: mysql:5.7
    container_name: db
    env_file: .env
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
      - ${LOGS_DIR}:/var/log/mysql
      - ./override-mysql:/etc/mysql/mysql.conf.d
    restart: always
    ports:
     - "${MYSQL_PORT}:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: redcap
#      MYSQL_USER: redcap
#      MYSQL_PASSWORD: redcap123


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
    - web
    - db
    env_file: .env
    restart: always
    ports:
    - 8080:80
  #    volumes:
  #      - /sessions


  cron:
    build: docker-cron
    env_file: .env
    command: ['crond', '-f', '/var/spool/cron/crontabs']
    depends_on:
      - web
      - db
    volumes:
      - ${CRONTAB_DIR}:/var/spool/cron/crontabs
      - ./override-cron/logrotate:/etc/logrotate.d
      - ${LOGS_DIR}:/logs-dir

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    depends_on:
      - web
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      # https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
      - MH_UI_WEB_PATH=mailhog

volumes:
  mysql-volume:
  logs-volume: