version: '3.7'
services:
  web:
    container_name: redcap_prod_web
    build: ./docker-web
    env_file: .env
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./redcap-overrides/web:/etc/container-config-override
      - ../credentials:/var/credentials
      - ../logs:/var/log/apache2
      - ../secrets:/var/secrets/
      - ../www:/var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: redcap_prod_db
    image: mysql:8.0
    env_file: ./.env
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ../logs/mysql:/var/log
      - mysql-volume:/var/lib/mysql
      - ./redcap-overrides/mysql/config:/etc/mysql/conf.d
      - ./redcap-overrides/mysql/scripts:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  cron:
    container_name: redcap_prod_cron
    build: ./docker-cron
    restart: always
    env_file: .env
    depends_on:
      - web
      - db
    volumes:
      - ../logs:/logs-dir

volumes:
  mysql-volume:
    name: "rdc_prod_mysql-volume"
  logs-volume:
    name: "rdc_prod_logs-volume"
